=== CRayFish07/Delta/src/com/delta/core/rover/delta.dtd
<!ELEMENT delta (settings,action*)>
        <!ELEMENT settings (welcome-page,handle-error,character-encoding,blacklist*)>

        <!ELEMENT welcome-page (#PCDATA)>
        <!ATTLIST welcome-page
                val CDATA #IMPLIED "/"
                >

        <!ELEMENT handle-error (#PCDATA)>
        <!ATTLIST handle-error
                val (true|false) "false"
                >

        <!ELEMENT character-encoding (#PCDATA)>
        <!ATTLIST character-encoding
                val CDATA #IMPLIED "UTF-8"
                >

        <!ELEMENT blacklist (#PCDATA)>


        <!ELEMENT action (service*,interceptor*)>
        <!ATTLIST action
                class CDATA #REQUIRED
                >

        <!ELEMENT service (dao*)>
        <!ATTLIST service
                class CDATA #REQUIRED
                impl CDATA #REQUIRED
                >

        <!ELEMENT dao EMPTY>
        <!ATTLIST dao
                class CDATA #REQUIRED
                impl CDATA #REQUIRED
                >

        <!ELEMENT interceptor (#PCDATA)>
        <!ATTLIST interceptor
                class CDATA #REQUIRED
                >

=== CRayFish07/Delta/src/delta.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE delta SYSTEM "src/com/delta/core/rover/delta.dtd">
<delta>
    <settings>
        <welcome-page>/index.jsp</welcome-page>
        <handle-error>true</handle-error>
        <devmode>false</devmode>
        <character-encoding>UTF-8</character-encoding>
        <blacklist>.jsp</blacklist>
        <blacklist>.html</blacklist>
    </settings>
    <action class="com.test.action.TestAction">
        <service class="com.test.service.TestService" impl="com.test.service.impl.TestServiceImpl">
            <dao class="com.test.dao.TestDao" impl="com.test.dao.impl.TestDaoImpl"/>
            <!--<dao class="com.test.dao.TestDao" impl="com.test.dao.impl.TestDaoImpl"/>-->
        </service>
        <!--<service class="com.test.service.TestService" impl="com.test.service.impl.TestServiceImpl">
            <dao class="com.test.dao.TestDao" impl="com.test.dao.impl.TestDaoImpl"/>
            <dao class="com.test.dao.TestDao" impl="com.test.dao.impl.TestDaoImpl"/>
        </service>-->
        <interceptor class="com.test.interceptor.TestInterceptor"/>
    </action>
    <action class="com.test.action.PlayAction"/>
</delta>
